# AMCL Configuration Parameters

amcl:
  ros__parameters:
    use_sim_time: true  # Use simulation time
    use_map_topic: false
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"
    global_frame_id: "map"
    laser_scan_topic: "scan"
    min_particles: 500
    max_particles: 2000
    kld_err: 0.05
    kld_z: 0.99
    update_min_d: 0.2
    update_min_a: 0.2
    resample_interval: 1
    transform_tolerance: 0.5
    recovery_alpha_slow: 0.0
    recovery_alpha_fast: 0.0
    laser_max_range: 12.0
    laser_min_range: 0.12
    laser_max_beams: 60
    sensor_model_type: "likelihood_field"