ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1

    two_d_mode: true
    transform_time_offset: 0.0

    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: map

    publish_tf: true
    map_frame: map

    # Odometry configuration
    odom0: /odom
    odom0_config: [false, false, false,
                   false, false, true,
                   true, true, false,
                   false, false, true,
                   false, false, false]
    odom0_queue_size: 5
    odom0_nodelay: false

    # Laser scan (if used)
    laser0: /scan
    laser0_queue_size: 5
    laser0_config: [false, false, false,
                    false, false, true,
                    true, true, false,
                    false, false, true,
                    false, false, false]
